alter table if exists hotel drop constraint if exists FK48m0ei7s6biikxbrku04slp0s;
alter table if exists room drop constraint if exists FKdosq3ww4h9m2osim6o0lugng8;
alter table if exists schedule drop constraint if exists FKh2hdhbss2x31ns719hka6enma;
alter table if exists schedule drop constraint if exists FKn78xyb9rkdia5mflu4t4kesji;
alter table if exists usr_role drop constraint if exists FKaa6ustx9bdadji6av4m6wvsg1;
drop table if exists address cascade;
drop table if exists hotel cascade;
drop table if exists room cascade;
drop table if exists schedule cascade;
drop table if exists usr cascade;
drop table if exists usr_role cascade;
create table address (id bigint generated by default as identity, city varchar(100) not null, country varchar(100) not null, number varchar(100) not null, street varchar(100) not null, primary key (id));
create table hotel (id bigint generated by default as identity, name varchar(100) not null, stars int8 not null, address_id bigint not null, primary key (id));
create table room (id bigint generated by default as identity, is_available boolean not null, number int8 not null, price int8 not null, hotel_id bigint not null, primary key (id));
create table schedule (id bigint generated by default as identity, rent_end date not null, rent_start date not null, room_id bigint not null, usr_id bigint not null, primary key (id));
create table usr (id bigint generated by default as identity, email varchar(100) not null, password varchar(100) not null, primary key (id));
create table usr_role (id bigint not null, roles varchar(255));
alter table if exists hotel add constraint UK_dcpycvarhghd0g3l6reewmsak unique (name);
alter table if exists usr add constraint UK_g9l96r670qkidthshajdtxrqf unique (email);
alter table if exists hotel add constraint FK48m0ei7s6biikxbrku04slp0s foreign key (address_id) references address;
alter table if exists room add constraint FKdosq3ww4h9m2osim6o0lugng8 foreign key (hotel_id) references hotel;
alter table if exists schedule add constraint FKh2hdhbss2x31ns719hka6enma foreign key (room_id) references room;
alter table if exists schedule add constraint FKn78xyb9rkdia5mflu4t4kesji foreign key (usr_id) references usr;
alter table if exists usr_role add constraint FKaa6ustx9bdadji6av4m6wvsg1 foreign key (id) references usr;

select id, country, city, street, number from address order by id;
select id, name, stars, address_id from hotel order by id;
select id, number, price, is_available, hotel_id from room order by id;
select id, email, password from usr order by id;
select id, roles from usr_role order by id;
select id, room_id, usr_id, rent_start, rent_end from schedule order by id;

select u.id, u.email, ur.roles
from usr as u
         inner join usr_role as ur on u.id = ur.id;

INSERT INTO public.address (country, city, street, "number") VALUES ('Germany', 'Berlin', 'Street A', '3');
INSERT INTO public.address (country, city, street, "number") VALUES ('Germany', 'Berlin', 'Street B', '7');
INSERT INTO public.address (country, city, street, "number") VALUES ('Germany', 'Berlin', 'Street C', '23');

INSERT INTO public.hotel (name, stars, address_id) VALUES ('Hotel X', 5, 1);
INSERT INTO public.hotel (name, stars, address_id) VALUES ('Hotel Z', 3, 2);
INSERT INTO public.hotel (name, stars, address_id) VALUES ('Hotel Y', 4, 3);

INSERT INTO public.room ("number", price, is_available, hotel_id) VALUES (101, 50, true, 1);
INSERT INTO public.room ("number", price, is_available, hotel_id) VALUES (102, 70, true, 1);
INSERT INTO public.room ("number", price, is_available, hotel_id) VALUES (201, 90, true, 1);

INSERT INTO public.room ("number", price, is_available, hotel_id) VALUES (101, 100, true, 2);
INSERT INTO public.room ("number", price, is_available, hotel_id) VALUES (102, 170, true, 2);
INSERT INTO public.room ("number", price, is_available, hotel_id) VALUES (201, 220, true, 2);

INSERT INTO public.room ("number", price, is_available, hotel_id) VALUES (101, 75, true, 3);
INSERT INTO public.room ("number", price, is_available, hotel_id) VALUES (102, 110, true, 3);
INSERT INTO public.room ("number", price, is_available, hotel_id) VALUES (201, 135, true, 3);

INSERT INTO public.usr (email, password) VALUES ('user@gmail.com', '$2a$10$9//0cxKPOONZoq0uajXH.eHAVAl.NyM.BZYXivt.DgNoTLHnCVMIi');
INSERT INTO public.usr_role (id, roles) VALUES (1, 'USER');
INSERT INTO public.usr_role (id, roles) VALUES (1, 'ADMIN');

insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (1, 1, '2020-04-01', '2020-04-03');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (1, 1, '2020-04-07', '2020-04-10');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (1, 1, '2020-04-15', '2020-04-20');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (2, 1, '2020-04-01', '2020-04-05');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (2, 1, '2020-04-06', '2020-04-11');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (2, 1, '2020-04-16', '2020-04-20');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (3, 1, '2020-04-01', '2020-04-03');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (3, 1, '2020-04-08', '2020-04-10');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (3, 1, '2020-04-13', '2020-04-16');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (4, 1, '2020-04-01', '2020-04-03');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (4, 1, '2020-04-08', '2020-04-15');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (4, 1, '2020-04-23', '2020-04-25');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (5, 1, '2020-04-01', '2020-04-05');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (5, 1, '2020-04-10', '2020-04-11');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (5, 1, '2020-04-14', '2020-04-22');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (6, 1, '2020-04-01', '2020-04-05');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (6, 1, '2020-04-10', '2020-04-11');
insert into schedule(room_id, usr_id, rent_start, rent_end) VALUES (6, 1, '2020-04-14', '2020-04-22');