-- Database: WorldwideHotelSystem
-- DROP DATABASE "WorldwideHotelSystem";
-- CREATE DATABASE "WorldwideHotelSystem"
--     WITH
--     OWNER = postgres
--     ENCODING = 'UTF8'
--     LC_COLLATE = 'English_United States.1252'
--     LC_CTYPE = 'English_United States.1252'
--     TABLESPACE = pg_default
--     CONNECTION LIMIT = -1;

DROP TABLE IF EXISTS public.usr_role;
DROP TABLE IF EXISTS public.schedule;
DROP TABLE IF EXISTS public.usr;
DROP TABLE IF EXISTS public.room;
DROP TABLE IF EXISTS public.hotel;


CREATE TABLE public.hotel
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    city character varying(100) COLLATE pg_catalog."default" NOT NULL,
    country character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "number" character varying(10) COLLATE pg_catalog."default" NOT NULL,
    stars integer NOT NULL,
    street character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT hotel_pkey PRIMARY KEY (id),
    CONSTRAINT uk_dcpycvarhghd0g3l6reewmsak UNIQUE (name)
)

    TABLESPACE pg_default;

ALTER TABLE public.hotel
    OWNER to postgres;


CREATE TABLE public.room
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    price integer NOT NULL,
    floor integer NOT NULL,
    "number" integer NOT NULL,
    is_available boolean NOT NULL,
    hotel_id bigint NOT NULL,
    CONSTRAINT room_pkey PRIMARY KEY (id),
    CONSTRAINT fkdosq3ww4h9m2osim6o0lugng8 FOREIGN KEY (hotel_id)
        REFERENCES public.hotel (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

    TABLESPACE pg_default;

ALTER TABLE public.room
    OWNER to postgres;


CREATE TABLE public.usr
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usr_pkey PRIMARY KEY (id),
    CONSTRAINT uk_dfui7gxngrgwn9ewee3ogtgym UNIQUE (username)
)

    TABLESPACE pg_default;

ALTER TABLE public.usr
    OWNER to postgres;


CREATE TABLE public.usr_role
(
    id bigint NOT NULL,
    roles character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT fkaa6ustx9bdadji6av4m6wvsg1 FOREIGN KEY (id)
        REFERENCES public.usr (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE public.usr_role
    OWNER to postgres;


CREATE TABLE public.schedule
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    rent_end date NOT NULL,
    rent_start date NOT NULL,
    room_id bigint NOT NULL,
    usr_id bigint NOT NULL,
    CONSTRAINT schedule_pkey PRIMARY KEY (id),
    CONSTRAINT fkh2hdhbss2x31ns719hka6enma FOREIGN KEY (room_id)
        REFERENCES public.room (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fkn78xyb9rkdia5mflu4t4kesji FOREIGN KEY (usr_id)
        REFERENCES public.usr (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

    TABLESPACE pg_default;

ALTER TABLE public.schedule
    OWNER to postgres;

insert into usr (username, password) values ('admin', '$2a$10$c4EN3FzBZolcHXzMxIobvetjEpTesqS03NMXxbYMlWTI4Waewzepe');
insert into usr_role (id, roles) values (1, 'ADMIN');
insert into usr (username, password) values ('moderator', '$2a$10$c4EN3FzBZolcHXzMxIobvetjEpTesqS03NMXxbYMlWTI4Waewzepe');
insert into usr_role (id, roles) values (2, 'MODERATOR');
insert into usr (username, password) values ('user', '$2a$10$c4EN3FzBZolcHXzMxIobvetjEpTesqS03NMXxbYMlWTI4Waewzepe');
insert into usr_role (id, roles) values (3, 'USER');

insert into hotel (city, country, name, number, stars, street) VALUES ('City1', 'Germany', 'hotel1', '11', 5, 'street1');
insert into hotel (city, country, name, number, stars, street) VALUES ('City1', 'Germany', 'hotel2', '12', 4, 'street2');
insert into hotel (city, country, name, number, stars, street) VALUES ('City1', 'Germany', 'hotel3', '13', 5, 'street3');
insert into hotel (city, country, name, number, stars, street) VALUES ('City2', 'Germany', 'hotel4', '21', 4, 'street1');
insert into hotel (city, country, name, number, stars, street) VALUES ('City2', 'Germany', 'hotel5', '22', 4, 'street2');
insert into hotel (city, country, name, number, stars, street) VALUES ('City2', 'Germany', 'hotel6', '23', 3, 'street3');
insert into hotel (city, country, name, number, stars, street) VALUES ('City3', 'Germany', 'hotel7', '31', 5, 'street1');
insert into hotel (city, country, name, number, stars, street) VALUES ('City3', 'Germany', 'hotel8', '32', 4, 'street2');
insert into hotel (city, country, name, number, stars, street) VALUES ('City3', 'Germany', 'hotel9', '33', 3, 'street3');

insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 101, 100, 1);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 102, 100, 1);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 103, 100, 1);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 104, 100, 1);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 201, 100, 1);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 202, 100, 1);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 203, 100, 1);

insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 101, 200, 2);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 102, 200, 2);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 103, 200, 2);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 104, 200, 2);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 201, 200, 2);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 202, 200, 2);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 203, 200, 2);

insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 101, 150, 3);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 102, 150, 3);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 103, 150, 3);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 104, 150, 2);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 201, 150, 3);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 202, 150, 3);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 203, 150, 3);

insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 101, 125, 4);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 102, 125, 4);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 103, 125, 4);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 104, 125, 4);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 201, 125, 4);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 202, 125, 4);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 203, 125, 4);

insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 101, 175, 5);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 102, 175, 5);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 103, 175, 5);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 104, 175, 5);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 201, 175, 5);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 202, 175, 5);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 203, 175, 5);

insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 101, 185, 6);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 102, 185, 6);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 103, 185, 6);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 104, 185, 6);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 201, 185, 6);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 202, 185, 6);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 203, 185, 6);

insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 101, 50, 7);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 102, 50, 7);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 103, 50, 7);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 104, 50, 7);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 201, 50, 7);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 202, 50, 7);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 203, 50, 7);

insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 101, 35, 8);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 102, 35, 8);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 103, 35, 8);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 104, 35, 8);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 201, 35, 8);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 202, 35, 8);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 203, 35, 8);

insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 101, 85, 9);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 102, 85, 9);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 103, 85, 9);
insert into room (floor, is_available, number, price, hotel_id) VALUES (1, true, 104, 85, 9);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 201, 85, 9);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 202, 85, 9);
insert into room (floor, is_available, number, price, hotel_id) VALUES (2, true, 203, 85, 9);

insert into schedule(rent_end, rent_start, room_id, usr_id) VALUES ('2020-04-03', '2020-04-01', 1, 1);
insert into schedule(rent_end, rent_start, room_id, usr_id) VALUES ('2020-04-10', '2020-04-07', 1, 2);
insert into schedule(rent_end, rent_start, room_id, usr_id) VALUES ('2020-04-20', '2020-04-15', 1, 3);

insert into schedule(rent_end, rent_start, room_id, usr_id) VALUES ('2020-04-05', '2020-04-01', 2, 1);
insert into schedule(rent_end, rent_start, room_id, usr_id) VALUES ('2020-04-11', '2020-04-06', 2, 2);
insert into schedule(rent_end, rent_start, room_id, usr_id) VALUES ('2020-04-20', '2020-04-16', 2, 3);

insert into schedule(rent_end, rent_start, room_id, usr_id) VALUES ('2020-04-03', '2020-04-01', 3, 1);
insert into schedule(rent_end, rent_start, room_id, usr_id) VALUES ('2020-04-10', '2020-04-08', 3, 2);
insert into schedule(rent_end, rent_start, room_id, usr_id) VALUES ('2020-04-16', '2020-04-13', 3, 3);

insert into schedule(rent_end, rent_start, room_id, usr_id) VALUES ('2020-04-03', '2020-04-01', 4, 1);
insert into schedule(rent_end, rent_start, room_id, usr_id) VALUES ('2020-04-15', '2020-04-08', 4, 2);
insert into schedule(rent_end, rent_start, room_id, usr_id) VALUES ('2020-04-25', '2020-04-23', 4, 3);

insert into schedule(rent_end, rent_start, room_id, usr_id) VALUES ('2020-04-05', '2020-04-01', 5, 1);
insert into schedule(rent_end, rent_start, room_id, usr_id) VALUES ('2020-04-11', '2020-04-10', 5, 2);
insert into schedule(rent_end, rent_start, room_id, usr_id) VALUES ('2020-04-22', '2020-04-14', 5, 3);
